### ISSUE TITLE
API Request: A way to specify non-interactive content in a pane

### ISSUE THREAD

**Issue by peterjcaulfield** [pmndrs/leva#112]
Use Case: I want to be able to add things to the pane that aren't controls.

E.g a diff showing the adjusted values from the original values.

In this case the pane would be dynamically updated but the content would be non-interactive.

There is a lot of value in the pane abstraction outside of the controls:

- the styles (the panes look great!)
- title bar
-  folders
- draggable behaviour

**Comment by gsimone** [comment]
It's interesting, this could be easily achieved via custom plugins: https://codesandbox.io/s/leva-custom-plugin-1iw37?file=/src/App.tsx:1464-1475

Your plugin could just be any react code that renders anything, really

**Comment by peterjcaulfield** [comment]
Great thanks for this. Will experiment with this during the week :)

**Comment by peterjcaulfield** [comment]
@gsimone is there a way to access the [store context](https://github.com/pmndrs/leva/blob/3031aea5f1e35ed1d9f8cd5f3b8c5730a636846d/packages/leva/src/context.tsx#L17) in a plugin?

**Comment by dbismut** [comment]
Hm there should be: https://codesandbox.io/s/focused-sun-f9f34

**Comment by peterjcaulfield** [comment]
Ah I think the issue is the dist tags for this package. If I do `npm i -S leva@latest` I get `0.3.2` but I can see `0.4.4` is published. Also `npm outdated` doesn't show me any new versions when I'm on `0.3.2`.

This export is resolved correctly with `0.4.4` 👍

**Comment by dbismut** [comment]
Oh that's weird. We still have some work to do on the ci/cd part.

**Comment by peterjcaulfield** [comment]
No worries I'll hopefully be able to contribute back a bit once I get my head around the code base a bit better 😄
